[spherical_color_bias]
# Class of the sampler. Must be of the form "your.module.YourSampler".
# The module must be importable from the current enviroment.
sampler = 'two4two.bias.MedVarSpherColorSampler'

# Save dataset to this directory.
output_dir = 'datasets/medvar_tests/spherical_color_bias'

# Should be an existing output_dir be overwritten? [Default: false]
force_overwrite = false

# Number of concurrent processes.
n_processes = 6

# Should blender be downloaded? [Default: false]
download_blender = true

# Should the blender output be printed? [Default: false]
 debug = false

# creates new dataset split names `train`.
[spherical_color_bias.train]
n_samples = 80_000

[spherical_color_bias.test]
n_samples = 3_000

[spherical_color_bias.validation]
n_samples = 500


[no_arms]
sampler = 'two4two.bias.MedVarNoArmsSampler'
output_dir = 'datasets/medvar_tests/no_arms'
n_processes = 6

[no_arms.train]
n_samples = 10

[no_arms.test]
n_samples = 3_000

[no_arms.validation]
n_samples = 500

[no_bias]
sampler = 'two4two.bias.MedVarSampler'
output_dir = 'datasets/medvar_tests/no_bias'
n_processes = 6

[no_bias.train]
n_samples = 10

[no_bias.test]
n_samples = 3_000

[no_bias.validation]
n_samples = 500


[spherical_bias]
sampler = 'two4two.bias.MedVarSpherSampler'
output_dir = 'datasets/medvar_tests/spherical_bias'
n_processes = 6

[spherical_bias.train]
n_samples = 10

[spherical_bias.test]
n_samples = 3_000

[spherical_bias.validation]
n_samples = 500


[color_bias]
sampler = 'two4two.bias.MedVarColorSampler'
output_dir = 'datasets/medvar_tests/color_bias'
n_processes = 6

[color_bias.train]
n_samples = 10

[color_bias.test]
n_samples = 3_000

[color_bias.validation]
n_samples = 500
